<?php
/**
 * @file
 * Code for the HumanitarianResponse Layout feature.
 */

include_once('humanitarianresponse_minimal_layout.features.inc');

/**
 * Implements hook_enable()
 */
function humanitarianresponse_minimal_layout_enable() {
  variable_set('theme_default', 'humanitarianresponse');
  // Enable the default theme.
  db_update('system')
    ->fields(array('status' => 1))
    ->condition('type', 'theme')
    ->condition('name', 'humanitarianresponse')
    ->execute();
  
  // Enable the admin theme.
  db_update('system')
    ->fields(array('status' => 1))
    ->condition('type', 'theme')
    ->condition('name', 'seven')
    ->execute();
}

